/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Modelo.Bacteriologa.Bacteriologa;
import Modelo.Bacteriologa.ConexionBacteriologa;
import Modelo.Medico.ConexionMedico;
import Modelo.Medico.Medico;
import Modelo.Paciente.ConexionPaciente;
import Modelo.Paciente.Paciente;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        tipoPersona = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        usuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        contraseña = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setLabelFor(contraseña);
        jLabel7.setText("Contraseña");

        jButton3.setText("Iniciar Sesión");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setLabelFor(usuario);
        jLabel6.setText("Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(usuario)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(21, 21, 21))
                    .addComponent(contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        tipoPersona.add(jRadioButton2);
        jRadioButton2.setText("Paciente");

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        tipoPersona.add(jRadioButton3);
        jRadioButton3.setText("Médico");

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        tipoPersona.add(jRadioButton4);
        jRadioButton4.setText("Bacterióloga");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Elige el tipo de persona");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel11)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2))
                .addGap(95, 95, 95))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 255));
        jButton4.setText("Registrarse");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Accede al sistema ingresando tu nombre de Usuario y Contraseña, además del tipo de");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("¡Bienvenido/a!");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("persona, si no tienes una cuenta, regístrate.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel10)))
                .addGap(93, 93, 93))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jButton4)))
                .addGap(38, 38, 38))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {  
        try{
            String seleccion = obtenerSeleccionado();
            switch (seleccion){
                case "Paciente":
                    RegistroPaciente rp = new RegistroPaciente(this);
                    this.setVisible(false);
                    rp.setLocationRelativeTo(null);
                    rp.setVisible(true);
                break;
                case "Médico":
                    RegistroMedico rm = new RegistroMedico(this);
                    this.setVisible(false);
                    rm.setLocationRelativeTo(null);
                    rm.setVisible(true);
                break;
                case "Bacterióloga":
                    RegistroBacteriologa rb = new RegistroBacteriologa(this);
                    this.setVisible(false);
                    rb.setLocationRelativeTo(null);
                    rb.setVisible(true);
                break;
                default:
                break;
            }
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(null, "Por favor elige un tipo de persona para comenzar el registro");
        }
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        String seleccion = obtenerSeleccionado();
        String usuario = this.usuario.getText();
        String password = new String(contraseña.getPassword());
        if (usuario == null || password == null) {
            JOptionPane.showMessageDialog(null, "Por favor llena ambos campos");
        } else {
            try {
                switch (seleccion) {
                    case "Paciente":
                        validarPaciente(usuario, password);
                        break;
                    case "Médico":
                        validarMedico(usuario, password);
                        break;
                    case "Bacterióloga":
                        validarBacteriologa(usuario, password);
                        break;
                    default:
                        break;
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Por favor elige un tipo de persona para iniciar sesión");
            }
        }
    }                                     

    private String obtenerSeleccionado(){
        String seleccionado = null;
        for (Enumeration<AbstractButton> buttons = tipoPersona.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                seleccionado = button.getText();
            }
        }
        return seleccionado;
    }
    
    private void validarPaciente(String usuario, String password) throws Exception {
        Paciente pac = new Paciente();
        Boolean encontrado = false;
        ConexionPaciente p = new ConexionPaciente();
        for (Paciente paciente : p.obtenerPacientes()) {
            if (paciente.getUsuario().equals(usuario) && paciente.getPassword().equals(password)) {
                pac = paciente;
                encontrado = true;
                SeleccionExamen v = new SeleccionExamen(pac);
                v.setLocationRelativeTo(null);
                v.setVisible(true);
                this.setVisible(false);
                break;
            }
        }
        if(encontrado == false){
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos.");
        }
    }
    
    private void validarMedico(String usuario, String password) {
        try {
            Medico med = new Medico();
            Boolean encontrado = false;
            ConexionMedico m = new ConexionMedico();
            for (Medico medico : m.obtenerMedicos()) {
                if (medico.getUsuario().equals(usuario) && medico.getPassword().equals(password)) {
                    med = medico;
                    encontrado = true;
                    VentanaMedico v = new VentanaMedico(med);
                    v.setLocationRelativeTo(null);
                    v.setVisible(true);
                    this.dispose();
                    break;
                }
            }
            if (encontrado == false) {
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void validarBacteriologa(String usuario, String password) throws Exception{
        Bacteriologa bac = new Bacteriologa();
        Boolean encontrado = false;
        ConexionBacteriologa b = new ConexionBacteriologa();
        for (Bacteriologa bacteriologa : b.obtenerBacteriologas()){
            if(bacteriologa.getUsuario().equals(usuario) && bacteriologa.getPassword().equals(password)) {
                bac = bacteriologa;
                encontrado = true;
                SeleccionRemision v = new SeleccionRemision(bac);
                v.setLocationRelativeTo(null);
                v.setVisible(true);
                this.setVisible(false);
                break;
            }
        }
        if(encontrado == false){
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos.");
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JTextField usuario;
    private javax.swing.ButtonGroup tipoPersona;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration                   
}
